### ISSUE TITLE
Redefinition of module 'ResearchKit' error

### ISSUE THREAD

**Issue by stevemoser** [carekit-apple/CareKit#149]
When building the sample app with Xcode 8.3 I get the following error:
Redefinition of module 'ResearchKit' error
In carekit/dependency/ResearchKit/module.modulemap:1:18:

**Comment by umerkhan-apple** [comment]
@stevemoser If you rename the module.modulemap file to ResearchKit.modulemap it should fix the compiler error.

**Comment by stevemoser** [comment]
@umerkhan-apple Thanks, that worked. Looks like someone reported this issue in the ResearchKit repo and it was closed but the issue still exists. https://github.com/ResearchKit/ResearchKit/issues/922

**Comment by umerkhan-apple** [comment]
@stevemoser Re-opened the previous issue on your request. Good call! However, I will go ahead and close this one as they both track the same issue.

**Comment by jzhw0130** [comment]
@umerkhan-apple 

Hi
Does the issue fixed?   Or need change the name?

Thanks
